version: '3.8'

services:
  finance-tracke-ml:
    image: tbished/finance-tracker-ml:latest
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models  # Persist trained models
      - ./.env:/app/.env:ro   # Mount env file if exists
    environment:
      - MODEL_DIR=/app/models
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:8080"]
      # Database configuration for future use
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=finance
      - DB_USER=finance-user
      - DB_PASSWORD=change_me
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped